"use client";

import { ArrowRight, ArrowUpRight, Bell, ChevronDown, Clock3, Eye, Flame, Info, LayoutDashboard, MoreHorizontal, RotateCcw, ShoppingBag, Sparkles, Star, Utensils, Vote } from "lucide-react";
import type { ReactNode } from "react";
import { candidates } from "@/data/candidates";
import { dishAnalytics, insights, overview } from "@/data/analytics";
import { getDish } from "@/data/dishes";
import { restaurant } from "@/data/restaurant";
import { AppRibbon, BrandMark, Pill } from "./shared";

function DashboardNav({ active, go }: { active: "overview" | "tests"; go: (href: string) => void }) {
  return <><div className="dashboard-mobile-top"><BrandMark compact /><Pill>Datos de ejemplo</Pill></div><aside className="dashboard-sidebar"><div className="dashboard-sidebar__brand"><BrandMark /></div><span className="sidebar-eyebrow">VISTA RESTAURANTE</span><nav><button className={active === "overview" ? "is-active" : ""} onClick={() => go("/carta/restaurante")}><LayoutDashboard size={17} /> Resumen</button><button className={active === "tests" ? "is-active" : ""} onClick={() => go("/carta/restaurante/pruebas")}><Sparkles size={17} /> Platos en prueba</button><button onClick={() => go("/carta")}><Utensils size={17} /> Ver carta <ArrowUpRight size={14} /></button></nav><div className="sidebar-restaurant"><span className="sidebar-restaurant__avatar">CB</span><span><strong>{restaurant.name}</strong><small>{restaurant.location}</small></span><MoreHorizontal size={16} /></div></aside></>;
}

function KpiCard({ label, value, sub, icon, featured = false }: { label: string; value: string; sub: string; icon: ReactNode; featured?: boolean }) {
  return <article className={"kpi-card" + (featured ? " kpi-card--featured" : "")}><div className="kpi-card__top"><span className="kpi-card__icon">{icon}</span><span className="kpi-card__spark">↗</span></div><span className="kpi-card__label">{label}</span><strong>{value}</strong><small>{sub}</small></article>;
}

function DashboardHeader({ title, subtitle, active, go }: { title: string; subtitle: string; active: "overview" | "tests"; go: (href: string) => void }) {
  return <header className="dashboard-header"><div><span className="dashboard-kicker"><span className="live-dot" /> RESUMEN DE CASA BRASA</span><h1>{title}</h1><p>{subtitle}</p></div><div className="dashboard-header__actions"><Pill>Datos de ejemplo</Pill><button className="period-select">Últimos 30 días <ChevronDown size={15} /></button><button className="dashboard-mobile-link" onClick={() => go(active === "overview" ? "/carta/restaurante/pruebas" : "/carta/restaurante")}><RotateCcw size={15} /></button></div></header>;
}

function InterestScoreCard() {
  return <article className="interest-score-card"><div className="interest-score-card__head"><div><span className="eyebrow-dark">PLATO DESTACADO</span><h2>Smash Trufa</h2></div><span className="dish-mini-art">🍔</span></div><div className="interest-score"><div><strong>8.7</strong><span>/ 10</span></div><p>Nivel de interés <b>Muy alto</b></p></div><div className="score-bar score-bar--large"><span style={{ width: "87%" }} /></div><p className="score-explainer"><Info size={14} /> Combina cuánto tiempo lo miraron, cuántas personas volvieron a verlo y cuántas lo agregaron al pedido.</p><div className="interest-metrics"><span><strong>7,1 s</strong><small>Tiempo mirando</small></span><span><strong>29%</strong><small>Volvieron a verlo</small></span><span><strong>24%</strong><small>Quisieron saber más</small></span><span><strong>14%</strong><small>Lo agregaron</small></span></div></article>;
}

function AttentionRanking() {
  return <article className="ranking-card"><div className="card-heading"><div><span className="eyebrow-dark">RANKING DE LA CARTA</span><h2>Los platos que más llaman la atención</h2></div><button className="more-button" aria-label="Más información"><Info size={16} /></button></div><div className="ranking-list">{dishAnalytics.slice(0, 6).map((item, index) => { const dish = getDish(item.slug); return dish ? <div className="ranking-row" key={item.slug}><span className="ranking-row__index">{String(index + 1).padStart(2, "0")}</span><span className="ranking-row__dish"><span className="ranking-row__emoji" style={{ background: "linear-gradient(145deg, " + dish.accent + ", #231a14)" }}>{dish.emoji}</span><strong>{dish.name}</strong></span><span className="ranking-row__tag">{item.label}</span><strong className="ranking-row__value">{item.avgAttention.toFixed(1).replace(".", ",")} s</strong></div> : null; })}</div></article>;
}

function InterestChoiceChart() {
  const points = [
    { name: "Smash Trufa", emoji: "🍔", left: "77%", bottom: "78%", tone: "orange" },
    { name: "Pizza Burrata", emoji: "🍕", left: "69%", bottom: "62%", tone: "orange" },
    { name: "Ravioles", emoji: "🍝", left: "42%", bottom: "60%", tone: "yellow" },
    { name: "Milanesa", emoji: "🥩", left: "55%", bottom: "42%", tone: "green" },
    { name: "Limonada", emoji: "🍋", left: "82%", bottom: "24%", tone: "green" },
    { name: "Tacos", emoji: "🌮", left: "29%", bottom: "27%", tone: "muted" },
  ];
  return <article className="chart-card"><div className="card-heading"><div><span className="eyebrow-dark">LECTURA SIMPLE</span><h2>Lo que llama la atención vs. lo que termina en el pedido</h2></div><button className="more-button" aria-label="Más información"><Info size={16} /></button></div><div className="scatter"><span className="scatter__axis scatter__axis--y">Cuánto interés genera</span><span className="scatter__axis scatter__axis--x">Cuánto lo eligen</span><span className="quadrant quadrant--tl">Atraen,<br />pero algo frena</span><span className="quadrant quadrant--tr">Estrellas</span><span className="quadrant quadrant--bl">Para revisar</span><span className="quadrant quadrant--br">Elección rápida</span>{points.map((point) => <span className={"scatter-point scatter-point--" + point.tone} style={{ left: point.left, bottom: point.bottom }} title={point.name} key={point.name}>{point.emoji}</span>)}</div><div className="chart-legend"><span><i className="legend-dot legend-dot--orange" />Smash Trufa</span><span><i className="legend-dot legend-dot--orange" />Pizza Burrata</span><span><i className="legend-dot legend-dot--yellow" />Ravioles</span><span><i className="legend-dot legend-dot--green" />Otros platos</span></div></article>;
}

function InsightCard({ title, body, tone }: { title: string; body: string; tone: string }) {
  return <article className={"insight-card insight-card--" + tone}><span className="insight-card__icon">{tone === "positive" ? "✦" : tone === "warm" ? "◒" : "⌁"}</span><span className="eyebrow-dark">LECTURA DEL MENÚ</span><h3>{title}</h3><p>{body}</p></article>;
}

function RevisitCard() {
  const revisits = [
    { name: "Cheesecake Pistacho", value: 31, emoji: "🍰", color: "#7f8960" },
    { name: "Smash Trufa", value: 29, emoji: "🍔", color: "#cf6846" },
    { name: "Pizza Burrata", value: 22, emoji: "🍕", color: "#be5d3d" },
    { name: "Ravioles", value: 17, emoji: "🍝", color: "#bb7d44" },
  ];
  return <article className="revisit-card"><div className="card-heading"><div><span className="eyebrow-dark">SEÑAL FUERTE DE INTERÉS</span><h2>Platos que vuelven a mirar</h2></div><span className="revisit-card__icon"><RotateCcw size={17} /></span></div><p className="card-lede">Cuando alguien retrocede en la carta para volver a ver un plato, es una señal fuerte de interés.</p><div className="revisit-list">{revisits.map((item) => <div key={item.name}><span className="revisit-list__dish"><span style={{ background: "linear-gradient(145deg, " + item.color + ", #2b211a)" }}>{item.emoji}</span><strong>{item.name}</strong></span><div className="revisit-list__bar"><i style={{ width: (item.value * 2.55) + "%" }} /></div><b>{item.value}%</b></div>)}</div></article>;
}

export function RestaurantOverview({ go }: { go: (href: string) => void }) {
  return <main className="dashboard-page"><AppRibbon restaurantView /><DashboardNav active="overview" go={go} /><div className="dashboard-content"><DashboardHeader title="Qué está pasando en tu carta" subtitle="Una forma simple de entender qué platos generan más interés antes de que el cliente termine de elegir." active="overview" go={go} /><section className="kpi-grid"><KpiCard label="Personas que abrieron la carta" value={overview.menuOpens.toLocaleString("es-UY")} sub="+18% vs. período anterior" icon={<Eye size={18} />} /><KpiCard label="Tiempo promedio mirando un plato" value={(overview.avgAttentionSeconds.toFixed(1).replace(".", ",") + " s")} sub="Casi 2 reproducciones completas" icon={<Clock3 size={18} />} /><KpiCard label="Plato que más atrapó" value={overview.topAttentionDish} sub={overview.topAttentionValue} icon={<Flame size={18} />} featured /><KpiCard label="Plato que más agregaron" value={overview.topAddedDish} sub={overview.topAddedValue} icon={<ShoppingBag size={18} />} /><KpiCard label="Plato que más volvieron a mirar" value={overview.topRevisitedDish} sub={overview.topRevisitedValue} icon={<RotateCcw size={18} />} /></section><section className="dashboard-grid dashboard-grid--top"><InterestScoreCard /><AttentionRanking /></section><section className="dashboard-grid dashboard-grid--wide"><InterestChoiceChart /><RevisitCard /></section><section className="insights-section"><div className="section-kicker">En lenguaje simple</div><div className="insights-grid">{insights.map((insight) => <InsightCard key={insight.title} title={insight.title} body={insight.body} tone={insight.tone} />)}</div></section><div className="dashboard-footer-link"><button onClick={() => go("/carta/restaurante/pruebas")}><Sparkles size={16} /> Ver qué plato conviene probar después <ArrowRight size={16} /></button></div></div></main>;
}

function CandidateRanking({ go }: { go: (href: string) => void }) {
  return <article className="candidate-ranking"><div className="card-heading"><div><span className="eyebrow-dark">RANKING DE IDEAS</span><h2>Personas que dicen “Lo pediría”</h2></div><button className="more-button" aria-label="Más información"><Info size={16} /></button></div><div className="candidate-ranking__rows">{candidates.map((candidate, index) => <button className="candidate-ranking__row" key={candidate.slug} onClick={() => go("/carta/proximamente/" + candidate.slug)}><span className="candidate-ranking__rank">0{index + 1}</span><span className="candidate-ranking__emoji" style={{ background: "linear-gradient(145deg, " + candidate.accent + ", #251a14)" }}>{candidate.emoji}</span><span className="candidate-ranking__name"><strong>{candidate.name}</strong><small>{candidate.votes} votos · {candidate.notifyCount} quieren aviso</small></span><span className="candidate-ranking__bar"><i style={{ width: candidate.wouldOrderPct + "%" }} /></span><strong className="candidate-ranking__pct">{candidate.wouldOrderPct}%</strong></button>)}</div></article>;
}

export function RestaurantTests({ go }: { go: (href: string) => void }) {
  return <main className="dashboard-page"><AppRibbon restaurantView /><DashboardNav active="tests" go={go} /><div className="dashboard-content"><DashboardHeader title="Qué plato debería llegar a la carta" subtitle="Compará el interés de tus próximas ideas antes de invertir en lanzarlas." active="tests" go={go} /><section className="kpi-grid kpi-grid--tests"><KpiCard label="Platos en prueba" value="3" sub="Ideas abiertas a votación" icon={<Sparkles size={18} />} /><KpiCard label="Votos recibidos" value="993" sub="Personas que opinaron" icon={<Vote size={18} />} /><KpiCard label="Quieren que les avises" value="374" sub="Interés para el lanzamiento" icon={<Bell size={18} />} /><KpiCard label="Candidato con más interés" value="Burger BBQ" sub="72% la pediría" icon={<Star size={18} />} featured /></section><section className="dashboard-grid dashboard-grid--tests"><div className="test-hero-card"><div className="test-hero-card__top"><Pill tone="accent">MEJOR CANDIDATO</Pill><span className="test-hero-card__star">✦</span></div><span className="eyebrow-dark">BURGER BBQ AHUMADA</span><h2>La idea con más fuerza<br /><em>para llegar a la carta.</em></h2><p>Combina el mayor porcentaje de personas que dicen que la pedirían, el mayor tiempo mirando y la mayor cantidad de personas que quieren que les avisemos.</p><div className="test-hero-card__stats"><span><strong>72%</strong><small>la pediría</small></span><span><strong>438</strong><small>votos</small></span><span><strong>186</strong><small>quieren aviso</small></span><span><strong>7,2 s</strong><small>mirando</small></span></div><button onClick={() => go("/carta/proximamente/burger-bbq-ahumada")}>Ver cómo se ve para el cliente <ArrowUpRight size={16} /></button></div><CandidateRanking go={go} /></section><section className="comparison-section"><div className="section-kicker">Una decisión más simple</div><div className="comparison-copy"><h2>Probá antes de<br /><em>incorporar.</em></h2><p>Los votos no reemplazan tu criterio. Te dan una señal rápida sobre qué idea vale la pena explorar primero.</p></div><div className="candidate-bars">{candidates.map((candidate, index) => <div className="candidate-bar-row" key={candidate.slug}><span className="candidate-bar-row__name"><b>0{index + 1}</b>{candidate.name}</span><div><i style={{ width: candidate.wouldOrderPct + "%" }} /></div><strong>{candidate.wouldOrderPct}%</strong></div>)}</div></section><div className="dashboard-footer-link"><button onClick={() => go("/carta")}><Utensils size={16} /> Volver a ver la carta como cliente <ArrowRight size={16} /></button></div></div></main>;
}
